name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install maven
        run: sudo apt install maven
      - name: Download the Java library and protobuf jar
        run: wget http://replomancer.net/OpenMined/libdifferentialprivacy-1.0.jar http://replomancer.net/OpenMined/libsummary-proto-speed.jar
      - name: Install the Java library to local Maven repo
        run: mvn install:install-file -Dfile=libdifferentialprivacy-1.0.jar -DgroupId=com.google.privacy.differentialprivacy -DartifactId=libdifferentialprivacy -Dversion=1.0 -Dpackaging=jar
      - name: Install the protobuf jar to local Maven repo
        run: mvn install:install-file -Dfile=libsummary-proto-speed.jar -DgroupId=com.google.differentialprivacy -DartifactId=libsummary-proto-speed -Dversion=1.0 -Dpackaging=jar
      - name: Install remaining dependencies
        run: lein deps
      - name: Check formatting
        run: lein cljfmt check
      - name: Run tests
        run: lein test
      - name: Generate coverage report
        run: lein cloverage --codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
